// user
export const SWITCH_LOGIN_REGISTER = 'SWITCH_LOGIN_REGISTER'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const SHOW_GREETING = 'SHOW_GREETING'
export const WRONG_AUTH_DATA = 'WRONG_AUTH_DATA'

// legal
export const GET_ISSUED_TOKENS = 'GET_ISSUED_TOKENS'