// user
export const SWITCH_LOGIN_REGISTER = 'SWITCH_LOGIN_REGISTER'
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const SHOW_GREETING = 'SHOW_GREETING'
export const SHOW_MARKETPLACE = 'SHOW_MARKETPLACE'
export const WRONG_AUTH_DATA = 'WRONG_AUTH_DATA'
export const TOGGLE_MARKET = 'TOGGLE_MARKET'

// legal
export const GET_ISSUED_TOKENS = 'GET_ISSUED_TOKENS'
export const SWITCH_TABLE_TYPE = 'SWITCH_TABLE_TYPE'
export const POST_ISSUED_TOKEN = 'POST_ISSUED_TOKEN'

// market
export const GET_MARKET_TOKENS = 'GET_MARKET_TOKENS'